### ISSUE TITLE
Problem with MTU size

### ISSUE THREAD

**Issue by TheHighestBit** [sparkleo-io/flutter_ota#18]
Hello,

When trying to use the package I ran into an issue with the to send length being too large. This seems weird to me since the log output correctly states that the MTU size is 255. Quickly looking at the package source there is a hardcoded MTU size of 400, which is used for calculations. After changing this to 250 everything seems to be working as expected. 
```
I/flutter (15025): Connected to device
I/flutter (15025): Connected. Starting update...
I/flutter (15025): Found service with correct UUID
I/flutter (15025): Found write characteristic
I/flutter (15025): Found notify characteristic
I/flutter (15025): Updating firmware...
I/flutter (15025): MTU size of current device 255
I/flutter (15025): Bin file after conversion is [233, 5, 2, 32, 212, 44, 8, 64, 238, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 1, 32, 0, 64, 63, 48, 69, 2, 0, 50, 84, 205, 171, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 115, 112, 45, 105, 100, 102, 58, 32, 118, 52, 46, 52, 46, 55, 32, 51, 56, 101, 101, 98, 97, 50, 49, 51, 97, 0, 0, 0, 0, 0, 0, 97, 114, 100, 117, 105, 110, 111, 45, 108, 105, 98, 45, 98, 117, 105, 108, 100, 101, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 50, 58, 51, 54, 58, 50, 52, 0, 0, 0, 0, 0, 0, 0, 0, 77, 97, 114, 32, 32, 53, 32, 50, 48, 50, 52, 0, 0, 0, 0, 0, 118, 52, 46, 52, 46, 55, 45, 100, 105, 114, 116, 121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 47, 52, 184, 41, 83, 238, 149, 148, 113, 151, 109, 169, 79, 153, 172, 237, 223, 46, 125, 229, 47, 66, 47, 41, 213, 158, 213, 83, 4, 228, 169, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
I/flutter (15025): Bin file length after conversion is 1094000
I/flutter (15025): before printing file Length
I/flutter (15025): this is the fileParts :  69
I/flutter (15025): this is file size : [254, 0, 16, 177, 112]
I/flutter (15025): this is otaInfo : [255, 0, 69, 1, 144]
I/flutter (15025): Parts are 40
I/flutter (15025): created 0 parts
I/flutter (15025): Before writing data, to send length is 402
I/flutter (15025): Writing part number 0 of 69 to ESP32
I/flutter (15025): Progress: 0%
E/flutter (15025): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(writeCharacteristic, data longer than allowed. dataLen: 402 > max: 252 (withResponse, noLongWrite), null, null)
E/flutter (15025): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
E/flutter (15025): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter (15025): <asynchronous suspension>
E/flutter (15025): #2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:603)
E/flutter (15025): <asynchronous suspension>
E/flutter (15025): #3      BluetoothCharacteristic.write (package:flutter_blue_plus/src/bluetooth_characteristic.dart:204)
E/flutter (15025): <asynchronous suspension>
E/flutter (15025): #4      BleRepository.writeDataCharacteristic (package:flutter_ota/ota_package.dart:45)
E/flutter (15025): <asynchronous suspension>
E/flutter (15025): #5      Esp32OtaPackage.sendPart (package:flutter_ota/ota_package.dart:278)
E/flutter (15025): <asynchronous suspension>
E/flutter (15025):
```

**Comment by Mir1001** [comment]
I can confirm this. It sets 402. If I set mtu 512 it still takes 402.

**Comment by umerasrar176** [comment]
Hi @TheHighestBit ! Thanks for reporting this and for taking the time to investigate the root cause.
You're absolutely right—the package previously used a hardcoded packet size, which could result in write requests exceeding the negotiated BLE MTU on some devices. As you found, this led to errors like:

`data longer than allowed. dataLen: 402 > max: 252`

This issue has since been resolved in the latest flutter_ota release (v1.0.0). The OTA transfer now dynamically adapts its packet size based on the negotiated MTU of the connected device, so it no longer relies on a hardcoded value.

Thanks again for identifying the problem and sharing the detailed logs—they were very helpful. If you update to the latest version, this issue should be resolved. Please let us know if you encounter any other problems or have additional feedback!
